name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    tags: ['*']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      pass: ${{ steps.check.outputs.pass }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # make sure fetched latest commit
      - name: Check
        id: check
        run: |
          if git log --format=%s -1 | grep -q '^docs' || ${{ github.ref_type == 'tag' }}; then
            echo "::set-output name=pass::true"
            echo "✅ latest commit is a docs commit/tag, building and deploying"
          else
            echo "::set-output name=pass::false"
            echo "⏭️ latest commit is not a docs commit/tag, skipping"
          fi

  build-and-deploy:
    needs: check
    if: needs.check.outputs.pass == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deploy-docs.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: install deps
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm run build
      - name: build docs
        run: pnpm run docs:build
      - name: upload docs
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/.vitepress/dist
      - name: deploy docs
        id: deploy-docs
        uses: actions/deploy-pages@v4
